/* Do not edit this file - Generated by Perlito5 9.0 */
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

MODULE = Some::Thing PACKAGE = Some::Thing
void foo ()
PPCODE:
    puts( SvPVx_nolen( newSVpv("MOO\x0a", 0)) );




