/* Do not edit this file - Generated by Perlito5 9.0 */
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

MODULE = ReturnHelloWorld PACKAGE = ReturnHelloWorld
void test ()
PPCODE:
    SV *something = newSVpv("Hello World", 0);
    PUSHs(something);




