
(defun slurp (filename) 
  (format nil "~{~a~%~}" 
    (with-open-file (s filename)
      (loop for line = (read-line s nil nil)
            while line
            collect line into lines
            finally (return lines)))))

(defun compiler-main ()
  (let (source (pos 0) p (arg1 "") (arg2 "") (result ""))
      (ignore-errors (setf arg1 (elt COMMON-LISP-USER::*posix-argv* 1)))
      (ignore-errors (setf arg2 (elt COMMON-LISP-USER::*posix-argv* 2)))
      (if (sv-eq arg1 "-e")
          (setf source arg2)
          (setf source (slurp arg1)))
      ;; (format t "~a" source)

      (setf result (concatenate 'string result (format nil "~a~%" "(progn ")))
      (setf result (concatenate 'string result (format nil "~a~%" ";; Do not edit this file - Generated by MiniPerl6")))
      (setf result (concatenate 'string result (format nil "~a~%" "(in-package mp-Main) (use-package 'common-lisp) (use-package 'mp-Main)")))
      (loop while (< pos (length source)) 
            do (progn
               (setf p (sv-comp_unit (proto-mp-MiniPerl6-Grammar) source pos))
               ;; (format t "~a~%" (sv-perl p))
               (setf result (concatenate 'string result  
                    (format nil "~a~%" (sv-emit (sv-capture p)))))
               ;; (sv-say (list ";; at source pos: " (sv-to p) " source end: " (length source)))
               (setf pos (sv-to p))))
      (setf result (concatenate 'string result (format nil "~a~%" ")")))
      ;; (format t "~a~%" result)

      ;; (format t "eval:~%")
      (in-package mp-Main)
      (ignore-errors (eval (read-from-string result)))

      ;; (format t "funcall:~%")
      ;; (funcall (read-from-string result))

      (sb-ext:quit)))

(sb-ext:save-lisp-and-die "mp6-lisp" :toplevel 'compiler-main :executable t )

