# Do not edit this file - Generated by Perlito5 9.0
use v6;
{
    package main {
        Any;
        # use feature
    }
    package Main {
        say('1..2');
        say('ok 1');
        print('o');
        say('k 2')
    }
}

