# Perlito5::AST::Do not edit this file - Generated by Perlito5 8.0
use v5;
use utf8;
use strict;
use warnings;
no warnings ('redefine', 'once', 'void', 'uninitialized', 'misc', 'recursion');
use Perlito5::Perl5::Runtime;
our $MATCH = Perlito5::Match->new();
package main;
use v5;
package Perlito5::AST::CompUnit;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub name {
    $_[0]->{'name'}
};
sub body {
    $_[0]->{'body'}
};
package Perlito5::AST::Val::Int;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub int {
    $_[0]->{'int'}
};
package Perlito5::AST::Val::Num;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub num {
    $_[0]->{'num'}
};
package Perlito5::AST::Val::Buf;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub buf {
    $_[0]->{'buf'}
};
package Perlito5::AST::Lit::Block;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub sig {
    $_[0]->{'sig'}
};
sub stmts {
    $_[0]->{'stmts'}
};
package Perlito5::AST::Index;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub obj {
    $_[0]->{'obj'}
};
sub index_exp {
    $_[0]->{'index_exp'}
};
package Perlito5::AST::Lookup;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub obj {
    $_[0]->{'obj'}
};
sub index_exp {
    $_[0]->{'index_exp'}
};
package Perlito5::AST::Var;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub sigil {
    $_[0]->{'sigil'}
};
sub namespace {
    $_[0]->{'namespace'}
};
sub name {
    $_[0]->{'name'}
};
package Perlito5::AST::Proto;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub name {
    $_[0]->{'name'}
};
package Perlito5::AST::Call;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub invocant {
    $_[0]->{'invocant'}
};
sub method {
    $_[0]->{'method'}
};
sub arguments {
    $_[0]->{'arguments'}
};
package Perlito5::AST::Apply;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub code {
    $_[0]->{'code'}
};
sub arguments {
    $_[0]->{'arguments'}
};
sub namespace {
    $_[0]->{'namespace'}
};
package Perlito5::AST::If;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub cond {
    $_[0]->{'cond'}
};
sub body {
    $_[0]->{'body'}
};
sub otherwise {
    $_[0]->{'otherwise'}
};
package Perlito5::AST::While;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub init {
    $_[0]->{'init'}
};
sub cond {
    $_[0]->{'cond'}
};
sub continue {
    $_[0]->{'continue'}
};
sub body {
    $_[0]->{'body'}
};
package Perlito5::AST::For;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub cond {
    $_[0]->{'cond'}
};
sub body {
    $_[0]->{'body'}
};
package Perlito5::AST::Decl;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub decl {
    $_[0]->{'decl'}
};
sub type {
    $_[0]->{'type'}
};
sub var {
    $_[0]->{'var'}
};
package Perlito5::AST::Sig;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub invocant {
    $_[0]->{'invocant'}
};
sub positional {
    $_[0]->{'positional'}
};
sub named {
    $_[0]->{'named'}
};
package Perlito5::AST::Sub;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub name {
    $_[0]->{'name'}
};
sub sig {
    $_[0]->{'sig'}
};
sub block {
    $_[0]->{'block'}
};
package Perlito5::AST::Do;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub block {
    $_[0]->{'block'}
};
package Perlito5::AST::Use;
sub new {
    ((my  $class) = shift());
    bless({@_}, $class)
};
sub mod {
    $_[0]->{'mod'}
};

1;
